### ISSUE TITLE
null value still not correctly parsed

### ISSUE THREAD

**Issue by weichen1984** [databricks/spark-csv#192]
In my CSV file, I have a column of float numbers, but when it's a missing value, it is filled with the string "null" without the quotes. I read somewhere in the Issues in the repo that the new spark csv 1.3.0 would address this problem. However I am still getting the error of 
```python
java.lang.NumberFormatException: For input string: "null"
```
The code I use is as follows:
```python
sqc.read
.format("com.databricks.spark.csv")
.options(header='false', delimiter="\t", nullValue='null')
.load(fn, schema=schema)
```

Thank you

**Comment by falaki** [comment]
You need to set the ```treatEmptyValuesAsNulls ``` option:
```scala
sqc.read
.format("com.databricks.spark.csv")
.options(header='false', delimiter="\t", nullValue='null', treatEmptyValuesAsNulls = 'true')
.load(fn, schema=schema)
```

**Comment by weichen1984** [comment]
Thank you falaki for replying. I tried the method you provided but it still didn't work. 
The file I am using is like this:
```python
10001,apple,304,red
10002,pear,203,yellow
10003,banana,null,yellow
```python

and the python code I used is:
```python
schm = StructType([
        StructField('pid', LongType(), True),
        StructField('fruit', StringType(), True),
        StructField('price', LongType(), True),
        StructField('color', StringType(), True)
    ])

df = (
    sqc.read
    .format("com.databricks.spark.csv")
    .options(
        header='false',
        delimiter=',',
        treatEmptyValuesAsNulls='true',
        nullValue='null'
    )
    .load('tmp2/csv_file.csv', schema=schm)
)

```

I am still getting this error:
```python
java.lang.NumberFormatException: For input string: "null"
```

**Comment by falaki** [comment]
Would you verify if you are using version 1.3.0?

**Comment by weichen1984** [comment]
This is how I start pyspark shell:

```bash
#!/bin/sh
pyspark \
--master yarn \
--deploy-mode client \
--num-executors 16 \
--executor-memory 3g \
--executor-cores 1 \
--packages com.databricks:spark-csv_2.11:1.3.0,com.databricks:spark-avro_2.10:1.0.0 \
--conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
--driver-memory=2g
```

**Comment by JoshRosen** [comment]
Proposal: how about writing a failing test and submitting a PR to see if the failure can be reproduced in Travis? That's probably the easiest way to move forward in terms of debugging and developing a fix if necessary.

**Comment by weichen1984** [comment]
Hi @JoshRosen how do I do that? what do I include in the PR?

**Comment by JoshRosen** [comment]
Hi @weichen1984,

Take a look at `AbstractCsvSuite` for examples of how to add tests to this library. In your case, I'd do the following:

- Create a new example CSV file in `src/test/resources` and name it after your test case.
- Add the filename to https://github.com/databricks/spark-csv/blob/84858ce5e78c024aa1682dcac82618e24a616f5e/src/test/scala/com/databricks/spark/csv/CsvSuite.scala#L41
- Add a new test case at the bottom of this file: https://github.com/databricks/spark-csv/blob/84858ce5e78c024aa1682dcac82618e24a616f5e/src/test/scala/com/databricks/spark/csv/CsvSuite.scala#L645

I think you can model your test case after the example that you gave upthread.

**Comment by ccann** [comment]
I have this same issue except with `FloatType()` and spark 1.5.2

**Comment by jarekszymczak** [comment]
I also have a problem with `DoubleType()`, Spark 1.4.1 called from Python, as per example from #164:

```python
trainSchema = StructType([
    StructField("UserID", DoubleType(), True), \
    StructField("UserAgentID", DoubleType(), True), \
    StructField("UserAgentOSID", DoubleType(), True), \
    StructField("UserDeviceID", DoubleType(), True), \
    StructField("UserAgentFamilyID", DoubleType(), True)
    ]
) 

train = sqlContext.read.format("com.databricks.spark.csv") \
        .option("header", "true") \
        .option("nullValue", "null") \
        .load("trainSet.csv", schema = trainSchema)

train.show(5)
```

and alternate version:
```python
train = sqlContext.read.format("com.databricks.spark.csv") \
        .option("header", "true") \
        .load("trainSet.csv", schema = trainSchema, nullValue='null')
```

Code yields an error:
 java.text.ParseException: Unparseable number: "null"

The csv file was created with use of this very same library with success. Lib is included via packages:
```
--packages com.databricks:spark-csv_2.11:1.3.0
```

**Comment by addisonj** [comment]
Taking a look at the code... It looks like `nullValue` is only ever used when *saving* a CSV, never when parsing...

It seems like this should support mapping a given nullValue into nulls, for example, I am trying to process files from postgres pgdump where nulls are `\N` and I don't see of a clean way to use this for all its niceties (mapping types, etc) with different null values... will dig into the code and see if I can submit a PR for this

**Comment by krvss** [comment]
Having the same problem with nullable LongType in Scala 2.10.4

Data to parse: 2015/12/31,1,social,108,24,0,0,3060,null

The last (problematic) field is declared as StructField("ii", LongType, nullable = true)

Spark 1.5.2, spark-csv: "spark-csv_2.10" version "1.2.0"

exception exceprt:

```
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:230)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:31)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:46)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:119)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:105)
```

**Comment by nizza** [comment]
I'm having the same problem on  _com.databricks:spark-csv_2.10:1.4.0_

`df = (sqlContext.read.format('com.databricks.spark.csv').
          options(header='false', inferschema='false', delimiter='\t', nullValue='NULL')...`

when trying to perform some operation on a float column, the following exception is thrown:

>  java.text.ParseException: Unparseable number: "NULL"
	at java.text.NumberFormat.parse(NumberFormat.java:385)
	at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$2.apply$mcF$sp(TypeCast.scala:56)
	at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$2.apply(TypeCast.scala:56)
	at com.databricks.spark.csv.util.TypeCast$$anonfun$castTo$2.apply(TypeCast.scala:56)
	at scala.util.Try.getOrElse(Try.scala:77)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:56)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:181)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:162)

**Comment by HyukjinKwon** [comment]
Let me take a look if I have some time.

**Comment by HyukjinKwon** [comment]
I could not reproduce this by following https://github.com/databricks/spark-csv/issues/192#issuecomment-159139373.

I used Spark 1.5.1 and CSV library 1.4.0.

**Comment by DivyaGe** [comment]
The issue is with CSV 1.3
Even I am facing the same issue

**Comment by HyukjinKwon** [comment]
This was fixed in https://github.com/databricks/spark-csv/pull/224. Can we maybe close this?

**Comment by dselivanov** [comment]
I can confirm, that this is fixed in 1.4 release.

**Comment by rachelwarren** [comment]
I am still seeing this issue when using Tab Delimited Data and where the last column contains a null value. 
The rows are being dropped with the DROPMALFORMED option.

**Comment by jlstack** [comment]
The treatEmptyValuesAsNulls helped me solve my problem, but this issue is the only place where I have seen it mentioned. It would be nice if this option was documented in the README.

**Comment by mbelsare** [comment]
The issue might be with the Datatypes of the schema that are being parsed against the Datatypes in the DataFrame.

Use "inferSchema"->"true" and the print the schema of the resulting Dataframe to understand the conflict

**Comment by rjurney** [comment]
I have the same issue in Spark 2.0.0 and CSV 2.10:1.4.0. This is still an issue.

**Comment by rachelwarren** [comment]
Sorry I got side tracked and didn't get around to this. I am still planning
on updating the fix for  2.0.0. I will try to move this up my todo list.

**Comment by kyrozetera** [comment]
Also ran into this issue when columns have a quoted empty string `""` in an `IntegerType` column. It works fine when it is blank without quotes, however. 

I get the following:

```
java.lang.NumberFormatException: null
``` 

I can work around it for now, but this has bit me a couple of times.

**Comment by shiplu** [comment]
@kyrozetera  Same for me. Then I removed the `"` character from. Now it works fine for me

**Comment by govindkothari** [comment]
@rachelwarren any update on this fix for spark 2.0 ?

**Comment by rachelwarren** [comment]
I am working on it. Should be done in the next week or so.

**Comment by kjoshi-rubikloud** [comment]
@rachelwarren any update on this?

**Comment by salimhamed** [comment]
@rachelwarren I'm running into this same issue and would appreciate an update.  Thanks!

**Comment by rachelwarren** [comment]
I have fixed it in this PR
https://github.com/rachelwarren/spark-csv/tree/rw-insertNullOnError but I
guess  that the project is no longer accepting submissions

**Comment by falaki** [comment]
@rachelwarren if you patch is just a bug fix (it does not change the interface or behavior of existing workloads), feel free to submit it. We still accept bug fixes for maintenance releases.

**Comment by arobinski** [comment]
@rachelwarren @falaki Is this bug fixed? Is the fix released, if yes - in which version?

**Comment by falaki** [comment]
@HyukjinKwon does https://github.com/databricks/spark-csv/pull/384 address this issue?

**Comment by karthik3010** [comment]
Hi Falaki,

In our case we have a different issue, the dataframe is converted as text file using 'com.databricks.spark.csv' API in java. But when a first column is empty in the source and after processing the file the second column is coming as first column. 

eg: 
lets assume pipe '|' as delimeter 
Column1|Column2     
     A|B
        |C
After processing and saving as file 
     A|B
     C|

Please suggest us on this.

**Comment by falaki** [comment]
What version of spark are you using? I recommend switching to latest Spark 2.x.

**Comment by karthik3010** [comment]
Im using 1.6.2 version of spark

**Comment by karthik3010** [comment]
Is there any solution for this?. We cannot migrate now to a newer version.

**Comment by HyukjinKwon** [comment]
I am sorry @falaki. I don't know why I missed your comment. I believe https://github.com/apache/spark/pull/15767 solves this. Let me check with this and leave another comment soon.

**Comment by HyukjinKwon** [comment]
Yea, this issue exists in this library. Let me open a PR to port this.

**Comment by HyukjinKwon** [comment]
Yea, it seems this issue exists. Let me open a PR after double checking.

**Comment by HyukjinKwon** [comment]
Ah, both issues are different. This case seems fixed as below:

```scala
    val schema = StructType(
      StructField("pid", LongType, true) ::
    StructField("fruit", StringType, true) ::
    StructField("price", LongType, true) ::
    StructField("color", StringType, true) :: Nil
    )
    val results = new CsvParser()
      .withSchema(schema)
      .withUseHeader(false)
      .withNullValue("null")
      .withParserLib(parserLib)
      .withParseMode(ParseModes.PERMISSIVE_MODE)
      .csvFile(sqlContext, boolFile)
      .show()
  }
```

prints

```
+-----+------+-----+------+
|  pid| fruit|price| color|
+-----+------+-----+------+
|10001| apple|  304|   red|
|10002|  pear|  203|yellow|
|10003|banana| null|yellow|
+-----+------+-----+------+
```

with the data below:

```
10001,apple,304,red
10002,pear,203,yellow
10003,banana,null,yellow
```

**Comment by HyukjinKwon** [comment]
I believe this one is closable.

**Comment by sumeet144** [comment]
I came across this similar issue with my data using pyspark. What I found is that to handle such behavior is to first read your csv files without schema and then, cast() to desired datatype for respective columns. spark.read.csv() will read csv files with string datatype and then, we can use withColumn() or other options to change datatype for your required columns like 

df = df.withColumn('col1', df['col1'].cast('int'))

Following this approach, I am able to resolve java.lang.NumberFormatException errors, which I was getting with pre-defined schema approach. Hope this will help someone. Thank you.
